### ISSUE TITLE
Crash while Searching

### ISSUE THREAD

**Issue by flipy34** [gfycat/gfycat-android-sdk#5]
Hi:

After further testing of 0.2.0 version, we have found a small bug when using the Picker Fragment Library the app is crashing.
The steps to reproduce are pretty easy:

1. Implement the Picker Fragment in your code.
2. Navigate to the Picker Fragment.
3. Click on the search widget.
4. Type anything
5. The app crashes.

I was able to get the crash log:
E/MessageQueue-JNI: com.gfycat.common.recycler.GroupAdapter$WrongGroupAdapterIndexAndRelativePositionException
                                                                                        at com.gfycat.common.recycler.GroupAdapter.getAdapterIndexAndRelativePosition(GroupAdapter.java:165)
                                                                                        at com.gfycat.common.recycler.GroupAdapter.onViewRecycled(GroupAdapter.java:84)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.dispatchViewRecycled(RecyclerView.java:6064)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(RecyclerView.java:5835)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.recycleCachedViewAt(RecyclerView.java:5730)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.recycleAndClearCachedViews(RecyclerView.java:5703)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.markKnownViewsInvalid(RecyclerView.java:6201)
                                                                                        at android.support.v7.widget.RecyclerView.markKnownViewsInvalid(RecyclerView.java:4171)
                                                                                        at android.support.v7.widget.RecyclerView.setDataSetChangedAfterLayout(RecyclerView.java:4155)
                                                                                        at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:4943)
                                                                                        at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:11357)
                                                                                        at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:6634)
                                                                                        at com.gfycat.common.recycler.GroupAdapter$LocalObserver.onChanged(GroupAdapter.java:240)
                                                                                        at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:11357)
                                                                                        at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:6634)
                                                                                        at com.gfycat.picker.category.CategoriesAdapter.filterData(CategoriesAdapter.java:101)
                                                                                        at com.gfycat.picker.category.CategoriesAdapter.filter(CategoriesAdapter.java:81)
                                                                                        at com.gfycat.picker.category.GfycatCategoriesFragment.setFilter(GfycatCategoriesFragment.java:161)
                                                                                        at com.gfycat.picker.GfycatPickerFragment.applyNewSearchQuery(GfycatPickerFragment.java:463)
                                                                                        at com.gfycat.picker.GfycatPickerFragment.access$200(GfycatPickerFragment.java:91)
                                                                                        at com.gfycat.picker.GfycatPickerFragment$1.onQueryTextChange(GfycatPickerFragment.java:428)
                                                                                        at com.gfycat.picker.search.DefaultSearchCategoryView$1.onTextChanged(DefaultSearchCategoryView.java:90)
                                                                                        at android.widget.TextView.sendOnTextChanged(TextView.java:7991)
                                                                                        at android.widget.TextView.handleTextChanged(TextView.java:8053)
                                                                                        at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10157)
                                                                                        at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1033)
                                                                                        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:559)
                                                                                        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
                                                                                        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:491)
                                                                                        at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:223)
                                                                                        at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:136)
                                                                                        at android.widget.TextView.doKeyDown(TextView.java:6098)
                                                                                        at android.widget.TextView.onKeyDown(TextView.java:5911)
                                                                                        at android.view.KeyEvent.dispatch(KeyEvent.java:2640)
                                                                                        at android.view.View.dispatchKeyEvent(View.java:9234)
                                                                                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                                        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                                        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2395)
                                                                                        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1727)
                                                                                        at android.app.Activity.dispatchKeyEvent(Activity.java:2725)
                                                                                        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:541)`

**Comment by trending-sense** [comment]
Is it 100% reproducible on your side? Or just specific string or characters?
Also have you noticed this issue on previous SDK builds? (if you used any lower then 0.2.0)
Thank you

**Comment by flipy34** [comment]
It is 100% reproducible, I just start typing on my emulator, it freezes and immediately after that it crash.
I will take a look and see if this is reproducible on 0.1.0 and 0.1.1

**Comment by flipy34** [comment]
So, I was able to reproduce the same issue on 0.1.0 version of the SDK, although it is throwing a different type of message despite that it is crashing in the same method.
`E/MessageQueue-JNI: java.lang.IllegalStateException: Unreachable 14 SingleCategoryAdapter 0 0 | CategoriesAdapter 1 1
                                                                                        at com.gfycat.common.recycler.GroupAdapter.getAdapterIndexAndRelativePosition(GroupAdapter.java:154)`

**Comment by trending-sense** [comment]
This looks like something very specific. @flipy34 could you also provide emulator specs so I could recreate the environment?
Meanwhile please try on another emulator and device.
Thank you!

**Comment by flipy34** [comment]
I was able also to make this happen on my OnePlus 3T, so I think it is not related to the actual type of device when testing. I think this could be some issues with the actual RecyclerView version of the support library. What version of the support library are you using?

**Comment by trending-sense** [comment]
We are using 25.1.0 but it will align with the one you use, in case if it is more recent.
It would be still very helpful if you could tell me **emulator specs** this issue is reproducible. So we could start from that.

**Comment by flipy34** [comment]
I am using the emulator with a Nexus 5X Frame(Not important I would assume), with Android OS 7.1.1 image with Google APIs Enabled, 1536 MB of RAM, 256 MB of VM Heap and 16384MB of internal memory plus another 16384MB of SD card Studio-managed space.

**Comment by trending-sense** [comment]
Support Library 25.4 and higher located and workaround introduced in gfycat-sdk-0.2.1 . Please use this version of our SDK in case if you will use mentioned support library version.
